package ProjectRoom;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Amelia ST10439947@vcconnect.edu.za ST10439947
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        QuitButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        UsernameLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        WelcomeLabel1 = new javax.swing.JLabel();
        WelcomeLabel2 = new javax.swing.JLabel();
        WelcomeLabel3 = new javax.swing.JLabel();
        WelcomeLabel4 = new javax.swing.JLabel();
        CircleBlockerPanel = new javax.swing.JPanel();
        BubblePic = new javax.swing.JLabel();
        MenuButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 400));
        jPanel1.setLayout(null);

        QuitButton.setBackground(new java.awt.Color(255, 122, 148));
        QuitButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        QuitButton.setForeground(new java.awt.Color(255, 255, 255));
        QuitButton.setText("Quit");
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(QuitButton);
        QuitButton.setBounds(360, 20, 70, 20);

        LoginButton.setBackground(new java.awt.Color(255, 142, 122));
        LoginButton.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setToolTipText("");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton);
        LoginButton.setBounds(180, 320, 90, 30);

        UsernameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel.setText("Username:");
        jPanel1.add(UsernameLabel);
        UsernameLabel.setBounds(120, 160, 100, 30);

        UsernameField.setBackground(new java.awt.Color(255, 255, 255));
        UsernameField.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameField);
        UsernameField.setBounds(120, 190, 210, 26);

        PasswordLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password:");
        jPanel1.add(PasswordLabel);
        PasswordLabel.setBounds(120, 220, 100, 30);

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField);
        PasswordField.setBounds(120, 250, 210, 26);

        WelcomeLabel1.setFont(new java.awt.Font("Lovelo Black", 0, 30)); // NOI18N
        WelcomeLabel1.setForeground(new java.awt.Color(255, 122, 148));
        WelcomeLabel1.setText("Welcome!");
        jPanel1.add(WelcomeLabel1);
        WelcomeLabel1.setBounds(110, 40, 190, 30);

        WelcomeLabel2.setFont(new java.awt.Font("Lovelo Black", 0, 30)); // NOI18N
        WelcomeLabel2.setForeground(new java.awt.Color(255, 142, 122));
        WelcomeLabel2.setText("Welcome!");
        jPanel1.add(WelcomeLabel2);
        WelcomeLabel2.setBounds(130, 60, 190, 31);

        WelcomeLabel3.setFont(new java.awt.Font("Lovelo Black", 0, 30)); // NOI18N
        WelcomeLabel3.setForeground(new java.awt.Color(255, 170, 96));
        WelcomeLabel3.setText("Welcome!");
        jPanel1.add(WelcomeLabel3);
        WelcomeLabel3.setBounds(150, 80, 190, 30);

        WelcomeLabel4.setBackground(new java.awt.Color(255, 255, 255));
        WelcomeLabel4.setFont(new java.awt.Font("Lovelo Black", 0, 30)); // NOI18N
        WelcomeLabel4.setForeground(new java.awt.Color(255, 219, 112));
        WelcomeLabel4.setText("Welcome!");
        jPanel1.add(WelcomeLabel4);
        WelcomeLabel4.setBounds(170, 100, 160, 30);

        CircleBlockerPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CircleBlockerPanelLayout = new javax.swing.GroupLayout(CircleBlockerPanel);
        CircleBlockerPanel.setLayout(CircleBlockerPanelLayout);
        CircleBlockerPanelLayout.setHorizontalGroup(
            CircleBlockerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        CircleBlockerPanelLayout.setVerticalGroup(
            CircleBlockerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(CircleBlockerPanel);
        CircleBlockerPanel.setBounds(190, 100, 30, 30);

        BubblePic.setIcon(new javax.swing.ImageIcon("C:\\Users\\swart\\OneDrive - ADvTECH Ltd\\Prog Java\\NetBeans\\Amelia_Swart_ST10439947_PROG5121_POE_Part1\\Pics\\Untitled design.png")); // NOI18N
        BubblePic.setText(" ");
        jPanel1.add(BubblePic);
        BubblePic.setBounds(60, 60, 320, 300);

        MenuButton.setBackground(new java.awt.Color(255, 122, 148));
        MenuButton.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        MenuButton.setForeground(new java.awt.Color(255, 255, 255));
        MenuButton.setText("Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MenuButton);
        MenuButton.setBounds(361, 360, 70, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//-------------------------------------------------------------------------------------------------------------------------------------------------
//Assign username and password variables and runs checks
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String userName;
        userName = UsernameField.getText();
        String passWord;
        passWord = PasswordField.getText();

        LoginRegisterClass login = new LoginRegisterClass();
        login.loginCheck(userName, passWord);
    }//GEN-LAST:event_LoginButtonActionPerformed
//-------------------------------------------------------------------------------------------------------------------------------------------------
    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        WelcomeFrame welcomeFrame = new WelcomeFrame();
        welcomeFrame.pack();
        welcomeFrame.setLocationRelativeTo(null);
        welcomeFrame.setDefaultCloseOperation(LoginFrame.DISPOSE_ON_CLOSE);
        setVisible(false);
        welcomeFrame.setVisible(true);
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BubblePic;
    private javax.swing.JPanel CircleBlockerPanel;
    public javax.swing.JButton LoginButton;
    private javax.swing.JToggleButton MenuButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton QuitButton;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel WelcomeLabel1;
    private javax.swing.JLabel WelcomeLabel2;
    private javax.swing.JLabel WelcomeLabel3;
    private javax.swing.JLabel WelcomeLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
